ansible_python_interpreter: /usr/bin/python3
become_pass: "{{ ansible_executor_become_pass }}"
k8s_cp: "172.16.1.2"
k8s_cp_port: 6443

kubernetes_kubeadm_init_extra_opts: "--cri-socket  /run/containerd/containerd.sock"
#used_eth_interface: "eth1"

helm_arch: arm64
docker_apt_arch: arm64