all:
  children:
    k8s_control_plane:
      hosts:
        k8s-cp:
    k8s_workers:
      hosts:
        k8s-worker:
    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers:
