ansible_host: 172.16.1.2
#ansible_user: ubuntu
#ansible_ssh_private_key_file: "~/ya_rsa"
ansible_user: vagrant
ansible_ssh_private_key_file: "./.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"

###################### Kubernetes variable ############################################
kubernetes_role: "master"
kubernetes_kubeproxy_mode: "ipvs"
kubernetes_apiserver_advertise_address: "{{ ansible_host }}"
kubernetes_cluster_domain_name: "cluster.local"
kubernetes_cgroupDriver: "systemd"
kubernetes_cri_socket: "/run/containerd/containerd.sock"
kubernetes_cluster_name: kubernetes
kubernetes_apiserver_certSANs:
  - 172.16.1.2
  - cluster-api.rand-k8s.tk
  - rand-k8s.tk
  - k8s-cp.k8ssubnet.openvpn.internal.oracle.com
